/**
 * Build a 160x144 frame-color mask from the ASCII reference.
 *
 *   ' ' (space)  -> WH (3)
 *   '·' (U+00B7) -> LG (2)
 *   '▓' (U+2593) -> DG (1)
 *   '█' (U+2588) -> BK (0)
 *   anything else -> 255 (camera area / unknown)
 *
 * Emits a packed Uint8Array as TypeScript source.
 */
import * as path from "node:path";
import * as fs from "node:fs";

const W = 160;
const H = 144;
const root = path.resolve(import.meta.dirname, "..", "..", "..");

const asciiPath = path.join(root, "supporting-materials", "frame_ascii.txt");
const raw = fs.readFileSync(asciiPath, "utf8");
// Split by newlines (handle \r\n)
const lines = raw.split(/\r?\n/);

const mask = new Uint8Array(W * H);
mask.fill(255);

const FRAME_THICK = 16;
const CAM_W = 128;
const CAM_H = 112;
// Camera area (inside the inner border): rows FRAME_THICK..FRAME_THICK+CAM_H-1
// and cols FRAME_THICK..FRAME_THICK+CAM_W-1. These pixels are unknown at
// correct time (they hold the actual picture) and must be excluded.
const camY0 = FRAME_THICK;
const camY1 = FRAME_THICK + CAM_H - 1;
const camX0 = FRAME_THICK;
const camX1 = FRAME_THICK + CAM_W - 1;

for (let y = 0; y < Math.min(lines.length, H); y++) {
  const line = lines[y];
  const chars = Array.from(line);
  for (let x = 0; x < W; x++) {
    if (y >= camY0 && y <= camY1 && x >= camX0 && x <= camX1) {
      mask[y * W + x] = 255;
      continue;
    }
    if (x >= chars.length) {
      mask[y * W + x] = 255;
      continue;
    }
    const ch = chars[x];
    let v: number;
    switch (ch) {
      case " ":
        v = 3; // WH
        break;
      case "·":
        v = 2; // LG
        break;
      case "▓":
        v = 1; // DG
        break;
      case "█":
        v = 0; // BK
        break;
      default:
        v = 255;
    }
    mask[y * W + x] = v;
  }
}

// Summary
const counts = [0, 0, 0, 0, 0];
for (let i = 0; i < mask.length; i++) {
  const v = mask[i];
  if (v < 4) counts[v]++;
  else counts[4]++;
}
console.log(
  `Mask built: BK=${counts[0]} DG=${counts[1]} LG=${counts[2]} WH=${counts[3]} unknown=${counts[4]}`,
);

// Emit a TypeScript file containing the mask as a base64-encoded array
const outPath = path.join(
  root,
  "packages",
  "gbcam-extract",
  "src",
  "frame-mask.ts",
);
const b64 = Buffer.from(mask).toString("base64");
const ts = `// AUTO-GENERATED by scripts/build-frame-mask.ts — do not edit.
// 160x144 frame palette mask:
//   0 = BK, 1 = DG, 2 = LG, 3 = WH, 255 = camera-area / unknown.

const _b64 =
  "${b64}";

export const FRAME_MASK_W = 160;
export const FRAME_MASK_H = 144;
export const FRAME_MASK: Uint8Array = Uint8Array.from(
  globalThis.atob
    ? globalThis.atob(_b64)
    : Buffer.from(_b64, "base64").toString("binary"),
  (c) => c.charCodeAt(0),
);
`;
fs.writeFileSync(outPath, ts);
console.log(`Wrote ${outPath}`);
