import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const projectRoot = path.join(__dirname, "../../../");
const sourceRoot = path.join(projectRoot, "supporting-materials/frames");
const sheetsRoot = path.join(sourceRoot, "sheets");
const individualRoot = path.join(sourceRoot, "individual");
const destPublic = path.join(__dirname, "../public/frames");
const destManifest = path.join(__dirname, "../src/generated/FrameSheets.ts");

const IMAGE_EXTS = new Set([".png", ".jpg", ".jpeg", ".gif", ".webp"]);

type FrameKind = "sheet" | "individual";

interface SheetEntry {
  url: string;
  stem: string;
  kind: FrameKind;
}

function walk(dir: string, out: string[] = []): string[] {
  if (!fs.existsSync(dir)) return out;
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const stat = fs.statSync(full);
    if (stat.isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

function collect(root: string, kind: FrameKind): SheetEntry[] {
  const entries: SheetEntry[] = [];
  if (!fs.existsSync(root)) return entries;
  for (const src of walk(root)) {
    const ext = path.extname(src).toLowerCase();
    if (!IMAGE_EXTS.has(ext)) continue;
    const rel = path.relative(sourceRoot, src);
    const dest = path.join(destPublic, rel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(src, dest);
    const url = "./frames/" + rel.split(path.sep).join("/");
    const stem = path.basename(rel, ext);
    entries.push({ url, stem, kind });
    console.log(`[copy-frames] ${src} -> ${dest}`);
  }
  // Stable order within a kind: alphabetical by stem so dedup tiebreaking is implicit.
  entries.sort((a, b) => a.stem.localeCompare(b.stem));
  return entries;
}

function main() {
  if (!fs.existsSync(sourceRoot)) {
    console.warn(`[copy-frames] No frames at ${sourceRoot}; skipping.`);
    fs.mkdirSync(path.dirname(destManifest), { recursive: true });
    fs.writeFileSync(
      destManifest,
      `// auto-generated — do not edit\nexport interface FrameSheetEntry { url: string; stem: string; kind: "sheet" | "individual"; }\nexport const FRAME_SHEETS: ReadonlyArray<FrameSheetEntry> = [];\n`,
      "utf-8",
    );
    return;
  }

  // Clear the destination so files removed/renamed at the source don't linger.
  fs.rmSync(destPublic, { recursive: true, force: true });
  fs.mkdirSync(destPublic, { recursive: true });
  fs.mkdirSync(path.dirname(destManifest), { recursive: true });

  const sheetEntries = collect(sheetsRoot, "sheet");
  const individualEntries = collect(individualRoot, "individual");
  // Sheets first, then individuals — the catalog relies on this order so
  // sheet frames appear before individual frames in the picker.
  const entries = [...sheetEntries, ...individualEntries];

  const manifest = `// auto-generated by scripts/copy-frames.ts — do not edit
export interface FrameSheetEntry {
  /** URL the browser fetches (relative to the deployed root). */
  url: string;
  /** Stem of the source PNG (used as the frame ID prefix). */
  stem: string;
  /**
   * "sheet" — image is a frame sheet containing many frames separated by a
   * background colour; processed via splitSheet.
   * "individual" — image is a single frame whose 128 × 112 hole is marked by
   * a uniform transparent or white region; processed via loadIndividualFrame.
   */
  kind: "sheet" | "individual";
}

export const FRAME_SHEETS: ReadonlyArray<FrameSheetEntry> = ${JSON.stringify(entries, null, 2)};
`;
  fs.writeFileSync(destManifest, manifest, "utf-8");
  console.log(`[copy-frames] wrote ${entries.length} entries to ${destManifest}`);
}

main();
