import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const projectRoot = path.join(__dirname, "../../../");
const sourceRoot = path.join(projectRoot, "supporting-materials/frames");
const destPublic = path.join(__dirname, "../public/frames");
const destManifest = path.join(__dirname, "../src/generated/FrameSheets.ts");

const IMAGE_EXTS = new Set([".png", ".jpg", ".jpeg", ".gif", ".webp"]);

interface SheetEntry {
  url: string;
  stem: string;
}

function walk(dir: string, out: string[] = []): string[] {
  if (!fs.existsSync(dir)) return out;
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const stat = fs.statSync(full);
    if (stat.isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

function main() {
  if (!fs.existsSync(sourceRoot)) {
    console.warn(`[copy-frames] No frames at ${sourceRoot}; skipping.`);
    fs.mkdirSync(path.dirname(destManifest), { recursive: true });
    fs.writeFileSync(
      destManifest,
      `// auto-generated — do not edit\nexport interface FrameSheetEntry { url: string; stem: string; }\nexport const FRAME_SHEETS: ReadonlyArray<FrameSheetEntry> = [];\n`,
      "utf-8",
    );
    return;
  }

  fs.mkdirSync(destPublic, { recursive: true });
  fs.mkdirSync(path.dirname(destManifest), { recursive: true });

  const all = walk(sourceRoot);
  const entries: SheetEntry[] = [];
  for (const src of all) {
    const ext = path.extname(src).toLowerCase();
    if (!IMAGE_EXTS.has(ext)) continue;
    const rel = path.relative(sourceRoot, src);
    const dest = path.join(destPublic, rel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(src, dest);
    const url = "./frames/" + rel.split(path.sep).join("/");
    const stem = path.basename(rel, ext);
    entries.push({ url, stem });
    console.log(`[copy-frames] ${src} -> ${dest}`);
  }

  // Stable order: alphabetical by stem so dedup tiebreaking is implicit.
  entries.sort((a, b) => a.stem.localeCompare(b.stem));

  const manifest = `// auto-generated by scripts/copy-frames.ts — do not edit
export interface FrameSheetEntry {
  /** URL the browser fetches (relative to the deployed root). */
  url: string;
  /** Stem of the source PNG (used as the frame ID prefix). */
  stem: string;
}

export const FRAME_SHEETS: ReadonlyArray<FrameSheetEntry> = ${JSON.stringify(entries, null, 2)};
`;
  fs.writeFileSync(destManifest, manifest, "utf-8");
  console.log(`[copy-frames] wrote ${entries.length} entries to ${destManifest}`);
}

main();
