import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const projectRoot = path.join(__dirname, "../../../");
const sourceRoot = path.join(projectRoot, "sample-pictures");
const destPublic = path.join(__dirname, "../public/sample-pictures");
const destManifest = path.join(
  __dirname,
  "../src/generated/SamplePictures.ts",
);

const IMAGE_EXTS = new Set([".png", ".jpg", ".jpeg", ".gif", ".webp"]);

interface SampleEntry {
  url: string;
  filename: string;
}

function walk(dir: string, out: string[] = []): string[] {
  if (!fs.existsSync(dir)) return out;
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const stat = fs.statSync(full);
    if (stat.isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

function main() {
  if (!fs.existsSync(sourceRoot)) {
    console.warn(
      `[copy-sample-pictures] No sample pictures at ${sourceRoot}; skipping.`,
    );
    fs.mkdirSync(path.dirname(destManifest), { recursive: true });
    fs.writeFileSync(
      destManifest,
      `// auto-generated — do not edit\nexport interface SamplePictureEntry { url: string; filename: string; }\nexport const SAMPLE_PICTURES: ReadonlyArray<SamplePictureEntry> = [];\n`,
      "utf-8",
    );
    return;
  }

  fs.mkdirSync(destPublic, { recursive: true });
  fs.mkdirSync(path.dirname(destManifest), { recursive: true });

  const all = walk(sourceRoot);
  const entries: SampleEntry[] = [];
  for (const src of all) {
    const ext = path.extname(src).toLowerCase();
    if (!IMAGE_EXTS.has(ext)) continue;
    const rel = path.relative(sourceRoot, src);
    const dest = path.join(destPublic, rel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(src, dest);
    const url = "./sample-pictures/" + rel.split(path.sep).join("/");
    const filename = path.basename(rel);
    entries.push({ url, filename });
    console.log(`[copy-sample-pictures] ${src} -> ${dest}`);
  }

  // Stable order: alphabetical by filename.
  entries.sort((a, b) => a.filename.localeCompare(b.filename));

  const manifest = `// auto-generated by scripts/copy-sample-pictures.ts — do not edit
export interface SamplePictureEntry {
  /** URL the browser fetches (relative to the deployed root). */
  url: string;
  /** Source filename including extension, e.g. "20260313_213416.jpg". */
  filename: string;
}

export const SAMPLE_PICTURES: ReadonlyArray<SamplePictureEntry> = ${JSON.stringify(entries, null, 2)};
`;
  fs.writeFileSync(destManifest, manifest, "utf-8");
  console.log(
    `[copy-sample-pictures] wrote ${entries.length} entries to ${destManifest}`,
  );
}

main();
