import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const projectRoot = path.join(__dirname, "../../../");
const readmePath = path.join(projectRoot, "README.md");
const outputPath = path.join(
  __dirname,
  "../src/generated/UserInstructions.tsx",
);
const assetsDir = path.join(__dirname, "../public/instructions-assets");

/**
 * Extract the "# User Instructions" section from README
 */
function extractUserInstructions(): string {
  const content = fs.readFileSync(readmePath, "utf-8");

  // Find the start of "# User Instructions"
  const startMarker = "# User Instructions";
  const startIndex = content.indexOf(startMarker);
  if (startIndex === -1) {
    throw new Error(
      "Could not find '# User Instructions' section in README.md",
    );
  }

  // Find the next level-1 heading (to know where the section ends)
  const afterStart = startIndex + startMarker.length;
  const nextH1 = content.indexOf("\n# ", afterStart);

  let sectionContent: string;
  if (nextH1 === -1) {
    // It's the last section
    sectionContent = content.substring(afterStart);
  } else {
    sectionContent = content.substring(afterStart, nextH1);
  }

  return sectionContent.trim();
}

/**
 * Process markdown: rewrite GitHub links and copy assets
 */
function processMarkdown(markdown: string): string {
  const githubBase =
    "https://github.com/tjcouch1/game-boy-camera-screenshot-extractor/blob/main/";
  const newBase = "./instructions-assets/";

  // Clear the destination so files removed/renamed at the source don't linger.
  fs.rmSync(assetsDir, { recursive: true, force: true });
  fs.mkdirSync(assetsDir, { recursive: true });

  // Find and copy all GitHub blob links
  const linkRegex = new RegExp(
    `${githubBase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}([^)\\s]+)`,
    "g",
  );

  let processed = markdown;
  const matches = markdown.matchAll(linkRegex);

  for (const match of matches) {
    let urlFilePath = match[1];
    // Decode URL-encoded characters
    let filePath = decodeURIComponent(urlFilePath);
    const oldUrl = match[0];
    const newUrl = newBase + urlFilePath;

    // Try to copy the file
    const sourceFile = path.join(projectRoot, filePath);
    if (fs.existsSync(sourceFile)) {
      const destFile = path.join(assetsDir, filePath);

      // Create subdirectories if needed in assets
      const destDir = path.dirname(destFile);
      if (!fs.existsSync(destDir)) {
        fs.mkdirSync(destDir, { recursive: true });
      }

      fs.copyFileSync(sourceFile, destFile);
      console.log(`Copied: ${sourceFile} -> ${destFile}`);
    } else {
      console.warn(`Source file not found: ${sourceFile}`);
    }

    // Replace the link in markdown
    processed = processed.replace(oldUrl, newUrl);
  }

  return processed;
}

/**
 * Escape markdown content for TypeScript string
 */
function escapeMarkdown(markdown: string): string {
  return markdown
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$/g, "\\$")
    .replace(/\n/g, "\\n");
}

/**
 * Generate the component file
 */
function generateComponent(markdownContent: string): string {
  const escapedMarkdown = escapeMarkdown(markdownContent);

  return `// This file is auto-generated by scripts/generate-instructions.ts
// Do not edit manually

export const USER_INSTRUCTIONS_MARKDOWN = \`${escapedMarkdown}\`;
`;
}

/**
 * Main execution
 */
async function main() {
  try {
    console.log("Extracting User Instructions from README.md...");
    const instructions = extractUserInstructions();

    console.log("Processing markdown and copying assets...");
    const processed = processMarkdown(instructions);

    console.log("Generating component file...");
    const component = generateComponent(processed);

    // Ensure output directory exists
    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, component, "utf-8");
    console.log(`Generated: ${outputPath}`);

    console.log("✓ Instructions generated successfully!");
  } catch (error) {
    console.error("Error generating instructions:", error);
    process.exit(1);
  }
}

main();
